#!/usr/bin/env python3
"""
Conversation Message Handler Hook

Handles sending messages to the workspace conversation inbox.
Appends formatted messages following the rules.

Usage:
    python3 message-handler.py --sender "username" --message "message content" [--thread "thread_name"] [--date "YYYY-MM-DD"]
"""

import argparse
import datetime
import os
from pathlib import Path

def format_message(sender, message, date_str):
    """Format a message according to the conversation template."""
    # Use green circle for user messages, blue for AI/system
    status_emoji = "🟢" if sender.lower() not in ["ai", "agent", "system"] else "🔵"

    formatted = f"@${sender} {status_emoji} _{date_str}_\n```\n{message}\n```\n---\n\n"

    return formatted

def append_to_inbox(formatted_message, inbox_path):
    """Append the formatted message to the inbox file."""
    with open(inbox_path, 'a', encoding='utf-8') as f:
        f.write(formatted_message)

def generate_ai_response(user_message):
    """
    Generate AI response placeholder.
    In the actual system, this should be handled by the main AI agent,
    not a hardcoded function. This is just a fallback.
    """
    # This function should not be used in production
    # AI responses should be generated by the main AI system
    return "[AI_RESPONSE_PLACEHOLDER]"

def main():
    parser = argparse.ArgumentParser(description='Conversation Message Handler Hook')
    parser.add_argument('--sender', required=True, help='Message sender')
    parser.add_argument('--message', required=True, help='Message content')
    parser.add_argument('--date', help='Date string (optional, defaults to today)')
    parser.add_argument('--ai-response', action='store_true', help='Generate AI response after user message')
    parser.add_argument('--target-agent', help='Specific agent to route message to for response')

    args = parser.parse_args()

    # Default date to today if not provided
    if not args.date:
        args.date = datetime.datetime.now().strftime('%Y-%m-%d')

    # Get inbox path relative to the script location
    script_dir = Path(__file__).parent.parent.parent.parent.parent  # to project root
    inbox_path = script_dir / 'workspace' / 'conversation' / '_inbox.md'

    # Format and append the original message
    formatted_message = format_message(args.sender, args.message, args.date)
    append_to_inbox(formatted_message, inbox_path)

    # Generate AI response if requested and sender is not AI
    if args.ai_response and args.sender.lower() not in ['ai', 'agent', 'system']:
        if args.target_agent:
            # Route to specific agent using the agent message router
            try:
                import subprocess
                import sys

                script_dir = Path(__file__).parent
                router_script = script_dir / 'agent-message-router.js'

                # Call the agent message router
                result = subprocess.run([
                    'node', str(router_script),
                    f'--agent={args.target_agent}',
                    f'--message={args.message}',
                    '--platform=conversation'
                ], capture_output=True, text=True, cwd=script_dir.parent.parent)

                if result.returncode == 0:
                    ai_response = result.stdout.strip()
                    # Extract just the response content (remove debug output)
                    if '--- RESPONSE ---' in ai_response:
                        ai_response = ai_response.split('--- RESPONSE ---')[-1].strip()
                    # Remove any leading/trailing debug output
                    lines = ai_response.split('\n')
                    # Find the actual response content (skip debug lines)
                    content_lines = []
                    in_response = False
                    for line in lines:
                        if line.strip() == '--- RESPONSE ---':
                            in_response = True
                            continue
                        if in_response and line.strip():
                            content_lines.append(line)
                    if content_lines:
                        ai_response = '\n'.join(content_lines).strip()
                else:
                    ai_response = f"[AGENT_ROUTING_ERROR: {result.stderr.strip()}]"

            except Exception as e:
                ai_response = f"[AGENT_ROUTING_FAILED: {str(e)}]"
        else:
            # Generate general AI response using the agent router with default agent
            try:
                import subprocess
                import sys

                script_dir = Path(__file__).parent
                router_script = script_dir / 'agent-message-router.js'

                # Call the agent message router with a general/default agent
                result = subprocess.run([
                    'node', str(router_script),
                    '--agent=general-assistant',  # Use general-assistant as default
                    f'--message={args.message}',
                    '--platform=conversation'
                ], capture_output=True, text=True, cwd=script_dir.parent.parent)

                if result.returncode == 0:
                    ai_response = result.stdout.strip()
                    # Extract just the response content (remove debug output)
                    if '--- RESPONSE ---' in ai_response:
                        # Split on --- RESPONSE --- and take everything after it
                        parts = ai_response.split('--- RESPONSE ---')
                        if len(parts) > 1:
                            ai_response = parts[1].strip()
                            # Remove the metadata part if it exists
                            if '\n---\n**Agent Metadata:**' in ai_response:
                                ai_response = ai_response.split('\n---\n**Agent Metadata:**')[0].strip()
                            elif '---\n**Agent Metadata:**' in ai_response:
                                ai_response = ai_response.split('---\n**Agent Metadata:**')[0].strip()
                else:
                    ai_response = f"[AI_RESPONSE_ERROR: {result.stderr.strip()}]"

            except Exception as e:
                ai_response = f"[AI_RESPONSE_FAILED: {str(e)}]"

        ai_formatted = format_message('AI', ai_response, args.date)
        append_to_inbox(ai_formatted, inbox_path)

        if args.target_agent:
            print(f"Message from {args.sender} appended. Response generated by {args.target_agent} agent")
        else:
            if ai_response.startswith('[') and ai_response.endswith(']'):
                print(f"Message from {args.sender} appended. AI response placeholder added - actual response should be generated by main AI system")
            else:
                print(f"Message from {args.sender} appended. AI response generated by general-assistant agent")
    else:
        print(f"Message from {args.sender} appended to workspace conversation inbox")

if __name__ == '__main__':
    main()